### ISSUE TITLE
Add a mailchimp form to the frontpage of the placeholder website

### ISSUE THREAD

**Issue by vosechu** [MLTSHP/placeholder_site#3]
@jessamyn would you be willing to create a mailchimp login for the group and invite me?

- [ ] Get a mailchimp account
- [ ] Update code
- [ ] Push to placeholder site

**Comment by ardgedee** [comment]
@vosechu @jessamynwest Is this issue resolvable?

**Comment by jessamynwest** [comment]
Yes!
